# Используем официальный образ PostgreSQL из Docker Hub
FROM postgres:latest

# Устанавливаем переменную окружения POSTGRES_USER для определения имени пользователя PostgreSQL
ENV POSTGRES_USER=admin

# Устанавливаем переменную окружения POSTGRES_PASSWORD для определения пароля пользователя PostgreSQL
ENV POSTGRES_PASSWORD=kQCGL9GROmUKv9vD

# Устанавливаем переменную окружения POSTGRES_DB для определения имени базы данных по умолчанию
ENV POSTGRES_DB=send_logs_db
