version: '3'

services:
  django_save_logs:
    build:
      context: .
      dockerfile: save_logs/Dockerfile
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - pgdb_save_logs

  pgdb_save_logs:
    build:
      context: postgresql
      dockerfile: Dockerfile
    container_name: postgres-container-send-logs
    ports:
      - "5433:5433"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kQCGL9GROmUKv9vD
      POSTGRES_DB: send_logs_db
      PGPORT: 5433
